version: "3"
services:
  db:
    restart: always
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=docker_test
    expose:
      - "5432"
  redis:
    restart: always
    image: redis:3.0
    expose:
      - "6379"
  web:
    # replace username/repo:tag with your name and image details
    image: docker_test
    ports:
      - "80:8000"
    environment:
      - DATABASE=db
    depends_on:
      - db
      - redis
    entrypoint: ./entry_point.sh
    command: uwsgi uwsgi.ini

  celery:
    image: docker_test
    container_name: cl01
    command: celery -A docker_test worker -l info
    links:
      - db
      - redis

  flower:
    image: docker_test
    container_name: cl02
    command: celery flower -A docker_test --port=5000
    links:
      - celery

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8000:80"
    depends_on:
      - web
    links:
      - web:web