version: "2"
services:
  db:
    restart: always
    container_name: docker_test-db
    image: postgres:9.6
    expose:
      - "5432"
    mem_limit: 30m
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=docker_test

  redis:
    restart: always
    image: redis:3.0
    expose:
      - "6379"
    mem_limit: 30m

  web:
    # replace username/repo:tag with your name and image details
    restart: always
    image: ballogy/docker_test:latest
    container_name: docker_test-container
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      - DATABASE=db
      - REDIS=redis
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=docker_test
    mem_limit: 300m
    depends_on:
      - db
      - redis
    command: sh -c "./entry_point.sh && gunicorn docker_test.wsgi:application -w 2 -b :8000 --timeout 120 --graceful-timeout 120 --worker-class gevent"

  celery:
    image: ballogy/docker_test:latest
    container_name: docker_test-celery
    command: celery -A docker_test worker --loglevel=info
    environment:
      - DATABASE=db
      - REDIS=redis
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=docker_test
    links:
      - db
      - redis
    mem_limit: 20m
    depends_on:
      - web
      - db
      - redis

  cbeat:
    image: ballogy/docker_test:latest
    container_name: docker_test-cbeat
    command: celery -A docker_test beat --loglevel=info
    links:
      - db
      - redis
    mem_limit: 20m
    environment:
      - DATABASE=db
      - REDIS=redis
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=docker_test
    depends_on:
      - web
      - db
      - redis

  flower:
    image: ballogy/docker_test:latest
    container_name: cl02
    command: celery flower -A docker_test --port=5000
    expose:
      - "5000"
    depends_on:
      - celery
